export const ex_java_plant_list = [
	["Ceratodon Purpureus", 									"Moos", 	"6", 		"gering", "Grün Braun Rosa", 	"Grün Braun", 			"sonnig halbschattig", 			"Immergrün "], 		
	["Ceratodon Purpureus 'conicus'", 							"Moos", 	"6",		"gering", "Braun", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "],
	["Bryum Argenteum", 										"Moos", 	"6", 		"gering", "Braun", 				"Grün grau", 			"halbschattig", 				"Immergrün "], 		
	["Bryum Capillare", 										"Moos", 	"5",		"gering", "Braun", 				"Grün Braun", 			"halbschattig schattig", 		"Immergrün "],
	["Hypnum Cupressiforme", 									"Moos", 	"5", 		"gering", "Braun",				"Grün",				"halbschattig", 				"Immergrün "],
	["Brachythecium i.S.", 										"Moos", 	"4 5 6 7", 	"gering", "Braun", 				"Grün Braun", 			"halbschattig schattig", 		"Immergrün "], 		
	["Melica Ciliata", 											"Staude", 	"6",		"mittel", "weiß", 				"Grün", 				"sonnig", 						"Sommergrün"],
	["Eriophyllum Lanatum", 									"Staude", 	"5", 		"gering", "gelb", 				"grau", 				"sonnig", 						"Wintergrün"], 		
	["Alyssum Montanum 'Berggold'",								"Staude", 	"6",		"gering", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"],
	["Sesleria Heufleriana (G)", 								"Staude", 	"5", 		"mittel", "Braun",				"grau",					"sonnig halbschattig", 			"Wintergrün"],
	["Achnatherum Calamagrostis Stipa Calamagrostis",		 	"Staude", 	"5 6 7", 	"gering", "weiß", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Poa Labillardieri (G)", 									"Staude", 	"6",		"mittel", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"],		
	["Aurinia Saxatilis Alyssum Saxatile", 						"Staude", 	"3",		"mittel", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"],
	["Dianthus Deltoides 'Leuchtfunk'", 						"Staude", 	"3", 		"mittel", "Rosa",				"Grün Braun",			"sonnig", 						"Wintergrün"],
	["Dianthus Knappii", 										"Staude", 	"3", 		"mittel", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Cerastium Biebersteinii", 								"Staude", 	"4", 		"gering", "weiß", 				"grau", 				"sonnig", 						"Wintergrün"], 		
	["Koeleria Glauca 'Heimische Wildstaude'", 					"Staude", 	"4",		"gering", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"],
	["Carex Oshimensis 'Evergold'", 							"Staude", 	"7", 		"gering", "gelb",				"Grün",				"sonnig halbschattig schattig", "Immergrün "], 		
	["Dryas Octopetala", 										"Gehoelz", 	"4 5 6 7 8","mittel", "weiß", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "],
	["Berberis Verruculosa", 									"Gehoelz", 	"5 6", 		"mittel", "gelb",				"Grün Braun",			"sonnig halbschattig", 			"Immergrün "],
	["Contoneaster Microphyllus 'Streibs Finding'", 			"Gehoelz", 	"7", 		"hoch", "weiß", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "], 		
	["Hypericum Kalmianum 'Gemo'", 								"Gehoelz", 	"5",		"mittel", "gelb", 				"Grün", 				"schattig", 					"Wintergrün"],
	["Juniperus Squamata 'Blue Star'", 							"Gehoelz", 	"5", 		"gering", "grau", 				"Grün", 				"sonnig halbschattig",			"Immergrün "], 		
	["Hypericum 'Hidcote'", 									"Gehoelz", 	"6",		"mittel", "gelb", 				"Grün gelb", 			"sonnig halbschattig schattig", "Wintergrün"],
	["Vibumum Odoratissimum", 									"Gehoelz", 	"8", 		"mittel", "weiß",				"Grün",				"sonnig halbschattig", 			"Immergrün "],
	["Euonymus Fortunei 'Coloratus'", 							"Gehoelz", 	"5 6 7 8", 	"gering", "gelb", 				"Grün Rosa", 			"sonnig halbschattig", 			"Immmergrün"], 		
	["Euonymus Fortunei 'Emerald Gaiety'", 						"Gehoelz", 	"5 6 7 8",	"gering", "gelb weiß", 			"Grün weiß violett", 	"sonnig halbschattig", 			"Immergrün "],
	["Euonymus Japonicus 'President Gauthier'", 				"Gehoelz", 	"6 7 8", 	"gering", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "], 		
	["Kerria Japonica 'Picta'", 								"Gehoelz", 	"5", 		"hoch", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Sommergrün"], 		
	["Juniperus Horizontalis 'Blue Chip'", 						"Gehoelz", 	"5", 		"gering", "gelb",				"Grün",				"sonnig halbschattig", 			"Immergrün "],
	["Sesleria Autumnalis (G)", 								"Staude", 	"7",		"mittel", "grau", 				"Grün", 				"sonnig halbschattig", 			"Wintergrün"],
	["Aubrieta Hybride 'Royal Blue'",							"Staude", 	"6",		"gering", "gelb", 				"violett", 				"sonnig", 						"Wintergrün"],
	["Carex Flacca (G)", 										"Staude", 	"5", 		"mittel", "gelb",				"Grün",				"sonnig halbschattig", 			"Sommergrün"],
	["Eriophyllum Lanatum", 									"Staude", 	"5", 		"mittel", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Delosperma Nubigenum", 									"Staude", 	"6",		"gering", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"],		
	["Festuca Cinerea 'Blauglut'", 								"Staude", 	"6",		"gering", "Braun", 				"Grün", 				"sonnig", 						"Wintergrün"],
	["Sedum Spectabile 'Brillant'", 							"Staude", 	"6", 		"mittel", "Rosa",				"Grün",				"sonnig", 						"Wintergrün"],
	["Sedum Spectabile 'Septemberglut'",						"Staude", 	"6", 		"mittel", "Rosa", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Yucca Filamentosa", 										"Staude", 	"6", 		"mittel", "gelb", 				"Grün Rosa grau", 		"sonnig", 						"Wintergrün"], 		
	["Yucca Filamentosa 'Golden Sword'", 						"Staude", 	"6",		"mittel", "weiß", 				"Grün", 				"sonnig", 						"Wintergrün"],
	["Delosperma Lineare", 										"Staude", 	"7", 		"gering", "gelb",				"Grün",				"sonnig", 						"Wintergrün"], 		
	["Festuca Amethystina (heimische Wildstaude)", 				"Staude", 	"4 5",		"gering", "violett", 			"Grün", 				"sonnig", 						"Wintergrün"],
	["Sedum Album 'Coral Carpet'", 								"Staude", 	"6",		"gering", "weiß", 				"Grün violett rot", 	"sonnig", 						"Wintergrün"],
	["Sedum Reflexum i.S.", 									"Staude", 	"7", 		"gering", "gelb", 				"grau Grün", 			"sonnig", 						"Wintergrün"], 		
	["Alyssum Montanum 'Berggold' ",							"Staude", 	"6",		"mittel", "gelb", 				"Grün", 				"sonnig", 						"Wintergrün"],
	["Festuca Mairei", 											"Staude", 	"7", 		"gering", "Grün",				"Grün",				"sonnig", 						"Wintergrün"],
	["Briza Media (heimische Wildstaude)", 						"Staude", 	"5", 		"mittel", "Grün", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Festuca Filiformis", 										"Staude", 	"5",		"gering", "Grün", 				"Grün", 				"sonnig", 						"Wintergrün"],		
	["Festuca Gautieri syn. Scoparia", 							"Staude", 	"5",		"gering", "Grün", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "],
	["Geranium x Cantabrigiense 'Biokovo'", 					"Staude", 	"5", 		"mittel", "Rosa",				"Grün",				"sonnig halbschattig", 			"Wintergrün"],
	["Geranium x Cantabrigiense 'Karmina'",						"Staude", 	"5", 		"mittel", "Rosa", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Sedum Spectabile 'Iceberg'", 								"Staude", 	"5", 		"mittel", "weiß", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Sesleria Heufleriana", 									"Staude", 	"5",		"mittel", "Braun", 				"Grün", 				"sonnig halbschattig", 			"Wintergrün"],
	["Helleborus Foetidus", 									"Staude", 	"6", 		"mittel", "Grün",				"Grün Braun",			"sonnig halbschattig",			 "Immergrün "], 		
	["Luzula Nivea (heimische Wildstaude)", 					"Staude", 	"6",		"mittel", "grau", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "],
	["Sedum Pachyclados", 										"Staude", 	"6", 		"gering", "Rosa",				"Grün",				"sonnig", 						"Wintergrün"],
	["Stipa (Nassella) Tenuifolia",								"Staude", 	"7", 		"mittel", "Braun", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Stipa Pulcherima f.nudicostata", 							"Staude", 	"7", 		"mittel", "grau", 				"Grün", 				"sonnig", 						"Wintergrün"], 		
	["Thymus Vulgaris", 										"Staude", 	"7",		"gering", "grau", 				"Grün", 				"sonnig", 						"Wintergrün Immergrün "],
	["Calamagrostis x Acutiflora 'Karl Foerster'", 				"Staude", 	"4 5 6", 	"mittel", "Braun",				"Grün",				"sonnig",						 "Wintergrün"], 		
	["Iberis Saxatilis (überhängend)", 							"Staude", 	"6", 		"gering", "weiß",				"Grün",				"sonnig", 						"Wintergrün"], 		
	["Sedum Hybridum", 											"Staude", 	"6",		"gering", "gelb", 				"Grün rot", 			"sonnig halbschattig", 			"Immergrün "],
	["Berberis Verruculosa", 									"Gehoelz", 	"5 6", 		"mittel", "gelb",				"Grün Braun",			"sonnig halbschattig", 			"Immergrün "],
	["Contoneaster Microphyllus 'Streibs Finding'", 			"Gehoelz", 	"7", 		"hoch", "weiß", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "], 		
	["Hypericum Kalmianum 'Gemo'", 								"Gehoelz", 	"5",		"mittel", "gelb", 				"Grün", 				"schattig", 					"Wintergrün"],
	["Juniperus Squamata 'Blue Star'", 							"Gehoelz", 	"5", 		"gering", "grau", 				"Grün", 				"sonnig halbschattig",			"Immergrün "], 		
	["Hypericum 'Hidcote'", 									"Gehoelz", 	"6",		"mittel", "gelb", 				"Grün gelb", 			"sonnig halbschattig schattig", "Wintergrün"],
	["Vibumum Odoratissimum", 									"Gehoelz", 	"8", 		"mittel", "weiß",				"Grün",				"sonnig halbschattig", 			"Immergrün "],
	["Euonymus Fortunei 'Coloratus'", 							"Gehoelz", 	"5 6 7 8", 	"gering", "gelb", 				"Grün Rosa", 			"sonnig halbschattig", 			"Immmergrün"], 		
	["Euonymus Fortunei 'Emerald Gaiety'", 						"Gehoelz", 	"5 6 7 8",	"gering", "gelb weiß", 			"Grün weiß violett", 	"sonnig halbschattig", 			"Immergrün "],
	["Euonymus Japonicus 'President Gauthier'", 				"Gehoelz", 	"6 7 8", 	"gering", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "], 		
	["Kerria Japonica 'Picta'", 								"Gehoelz", 	"5", 		"hoch", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Sommergrün"], 		
	["Juniperus Horizontalis 'Blue Chip'", 						"Gehoelz", 	"5", 		"gering", "gelb",				"Grün",				"sonnig halbschattig", 			"Immergrün "],
	["Lonicera Pileata", 										"Gehoelz", 	"6", 		"hoch", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Immergrün  Wintergrün"], 		
	["Cotoneaster Dammeri i.S.", 								"Gehoelz", 	"5 6",		"mittel", "weiß", 				"Grün", 				"sonnig halbschattig schattig", "Immergrün  Wintergrün"],
	["Juniperus Media 'Pfitzeriana Compacta'", 					"Gehoelz", 	"5", 		"gering", "gelb", 				"Grün", 				"sonnig halbschattig",			"Immergrün "], 		
	["Juniperus x Media 'Gold Coast'", 							"Gehoelz", 	"5",		"gering", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "],
	["Ligustrum Vulgare 'Lodense'", 							"Gehoelz", 	"5", 		"hoch", "weiß",					"Grün Braun",			"sonnig halbschattig", 			"Sommergrün Wintergrün"],
	["Cotoneaster Microphyllus 'Cochleatus' ", 					"Gehoelz", 	"7", 		"hoch", "weiß", 				"Grün Braun", 			"sonnig halbschattig", 			"Immmergrün"], 		
	["Cotoneaster Conspicuus 'Decorus'", 						"Gehoelz", 	"5", 		"hoch", "weiß", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "], 		
	["Berberis Buxifolia 'Nana'", 								"Gehoelz", 	"5", 		"gering", "gelb", 				"Grün Braun", 			"sonnig halbschattig", 			"Immergrün "], 		
	["Berberis Thunbergii 'Atropurpurea Nana'", 				"Gehoelz", 	"5", 		"gering", "gelb",				"Grün rot gelb",		"sonnig", 						"Sommergrün"],
	["Cotoneaster Microphyllus 'Streibs Findling'", 			"Gehoelz", 	"7", 		"mittel", "weiß", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "], 		
	["Erica i.S.", 												"Gehoelz", 	"6",		"mittel", "gelb grau Rosa", 	"Grün Braun", 			"sonnig", 						"Immergrün "],
	["Hypericum  Calycinum", 									"Gehoelz", 	"6", 		"mittel", "gelb", 				"Grün", 				"sonnig halbschattig schattig",	"Wintergrün"], 		
	["Pyracantha Coccinea 'Red Column'", 						"Gehoelz", 	"6",		"hoch", "weiß", 				"Grün", 				"sonnig halbschattig", 			"Immergrün  Wintergrün"],
	["Pyracantha Coccinea 'Golden Charmer'", 					"Gehoelz", 	"6", 		"gering", "weiß",				"Grün",				"sonnig halbschattig", 			"Immergrün  Wintergrün"],
	["Pyracantha Coccinea 'Orange Charmer'", 					"Gehoelz", 	"6", 		"gering", "weiß",				"Grün",				"sonnig halbschattig", 			"Immergrün  Wintergrün"],
	["Cytisus Scoparius 'Boskoop Ruby'", 						"Gehoelz", 	"6",		"hoch", "Rosa", 				"Grün", 				"sonnig", 						"Sommergrün"],
	["Cytisus Scoparius 'Roter Favorit", 						"Gehoelz", 	"6", 		"mittel", "Rosa", 				"Grün", 				"sonnig", 						"Sommergrün"], 		
	["Cytisus scoparius 'Golden Cascade'", 						"Gehoelz", 	"7", 		"mittel", "gelb", 				"Grün", 				"sonnig", 						"Immergrün "], 		
	["Lespedeza Thunbergii", 									"Gehoelz", 	"7", 		"hoch", "Rosa",					"Grün gelb",			"sonnig", 						"Sommergrün"],
	["Viburnum x Burkwoodii", 									"Gehoelz", 	"6",		"gering", "weiß Rosa", 			"Grün orange", 		"sonnig halbschattig", 			"Wintergrün"],
	["Ilex Aquifolium 'Argentea Marginata' ", 					"Gehoelz", 	"7", 		"mittel", "weiß", 				"Grün", 				"halbschattig schattig",		"Immergrün "], 		
	["Juniperus Conferta 'Blue Pacific'", 						"Gehoelz", 	"5 6 7 8",	"mittel", "gelb", 				"Grün", 				"sonnig",						"Immergrün "],
	["Jasminum Nudiflorum", 									"Gehoelz", 	"7", 		"mittel", "gelb",				"Grün",				"sonnig halbschattig", 			"Sommergrün"],
	["Lonicera Nitida 'MaiGrün'", 								"Gehoelz", 	"7", 		"gering", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Immmergrün Wintergrün"], 		
	["Cornus Sangiduinea 'Midwinter Fire'", 					"Gehoelz", 	"4",		"gering", "weiß", 				"Grün rot orange", 	"sonnig halbschattig", 			"Sommergrün"],
	["Callicarpa Bodinieri Giraldii 'Profusion'", 				"Gehoelz", 	"6", 		"hoch", "violett Rosa", 		"Grün gelb orange", 	"sonnig halbschattig", 			"Sommergrün"], 		
	["Chamaecyparis Pisifera 'Sungold'", 						"Gehoelz", 	"4", 		"gering", "violett", 			"Grün", 				"sonnig", 						"Immergrün "], 		
	["Calluna Vulgaris", 										"Gehoelz", 	"6", 		"mittel", "Rosa",				"Grün",				"sonnig", 						"Immergrün "],
	["Daboecia i.S", 											"Gehoelz", 	"7", 		"hoch", "weiß violett Rosa", 	"Grün Braun", 			"sonnig", 						"Immergrün "], 		
	["Berberis Frikartii Verrucandi", 							"Gehoelz", 	"6", 		"gering", "gelb", 				"Grün", 				"sonnig halbschattig", 			"Immergrün "] 		
];
